curl 'http://localhost:8910/.redwood/functions/graphql' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryxAoe6JrPlUp3LDGd' \
  -H 'Cookie: auth-provider=dbAuth; session_8911=xlPSO79++Zl0P9arqfPdT0ifzMespTgmxEdDBT52OOvuyTeFK6smp+YJYB4nZyEij0jlmd/cigiXS8/+5aDnWw==|zuRh/q5FytIrjcHgKMA38A==' \
  -H 'Origin: http://localhost:8910' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:8910/folder/1' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'------WebKitFormBoundaryxAoe6JrPlUp3LDGd\r\nContent-Disposition: form-data; name="operations"\r\n\r\n{"operationName":"UpdateFolderMutation","variables":{"id":1,"input":{"files":null}},"query":"mutation UpdateFolderMutation($id: Int\u0021, $input: UpdateFolderInput\u0021) {\\n  updateFolder(id: $id, input: $input) {\\n    id\\n    files {\\n      id\\n      path\\n      __typename\\n    }\\n    __typename\\n  }\\n}"}\r\n------WebKitFormBoundaryxAoe6JrPlUp3LDGd\r\nContent-Disposition: form-data; name="map"\r\n\r\n{"1":["variables.input.files"]}\r\n------WebKitFormBoundaryxAoe6JrPlUp3LDGd\r\nContent-Disposition: form-data; name="1"; filename="s1.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryxAoe6JrPlUp3LDGd--\r\n'
